[package]
name = "cairo-lang-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax representation."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.10.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.0" }
cairo-lang-primitive-token.workspace = true
||||||| 3d5631d3f
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.10.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.0" }
cairo-lang-primitive-token = { path = "../cairo-lang-primitive-token", version = "1.0.0"}
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.10.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.1" }
cairo-lang-primitive-token = { path = "../cairo-lang-primitive-token", version = "1.0.0"}
>>>>>>> origin/dev-v2.10.1
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
salsa.workspace = true
smol_str.workspace = true
unescaper.workspace = true
serde = { workspace = true, default-features = true }

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
