[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.11.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.11.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.11.4" }
salsa.workspace = true
||||||| b34dbfaa1
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.11.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.11.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.11.4" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0" }
>>>>>>> origin/dev-v2.12.0
itertools = { workspace = true, default-features = true }

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
