[package]
name = "cairo-lang-eq-solver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Equation solving for Sierra generation."

[dependencies]
<<<<<<< HEAD
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.0" }
||||||| 83124a92b
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.9.3" }
=======
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.9.4" }
>>>>>>> origin/dev-v2.9.4
good_lp.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true
