[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"

[dependencies]
anyhow.workspace = true
<<<<<<< HEAD
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.10.0" }
||||||| 83124a92b
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.9.3" }
=======
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.9.4" }
>>>>>>> origin/dev-v2.9.4
clap.workspace = true
serde_json.workspace = true
