[package]
name = "generate-syntax"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
log.workspace = true

<<<<<<< HEAD
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.10.0", features = [
||||||| 83124a92b
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.3", features = [
=======
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.4", features = [
>>>>>>> origin/dev-v2.9.4
    "env_logger",
] }
<<<<<<< HEAD
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "~2.10.0" }
||||||| 83124a92b
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "~2.9.3" }
=======
cairo-lang-syntax-codegen = { path = "../../cairo-lang-syntax-codegen", version = "~2.9.4" }
>>>>>>> origin/dev-v2.9.4
