[package]
name = "cairo-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo compiler executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.10.0" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.10.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.10.0", features = [
||||||| 83124a92b
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.3" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.9.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.3", features = [
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.4" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.9.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.4", features = [
>>>>>>> origin/dev-v2.9.4
    "env_logger",
] }
